### PR TITLE
Rename FooAbstract to AbstractFoo [#17]

### PR DESCRIPTION
**Pull request by q-hung**
Changes proposed in this pull request:
* Rename FooAbstract to AbstractFoo
* I'm not sure why we have `NodeFieldAbstractAbstract` in the first place.
@Jalle19  Could you please suggest some ideas how to write unit tests for those fields?

### CODE REVIEW

**Comment by cniska** [comment]
LGTM

**Review by cniska — APPROVED** [review]

**Comment by Jalle19** [comment]
@hungneox not sure yet, I have to get used to the library first

**Review by Jalle19 — APPROVED** [review]

**Comment by q-hung** [comment]
Note that for the `suggest`
> The format is like package links above, except that the values are free text and not version constraints.
https://getcomposer.org/doc/04-schema.md#suggest
Therefore, I also changed that.

**Comment by q-hung** [comment]
This closes #17, closes #20

**Pull request merged**
